### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by manchilds** [lol-jude/Blooket-Hacks#100]
<img width="442" alt="Screen Shot 2022-05-03 at 8 10 32 PM" src="https://user-images.githubusercontent.com/104856526/166504271-87019651-a3a3-4c01-adfd-23ff8c7820cf.png">

**Comment by manchilds** [comment]
i am confused of what this means

**Comment by lol-jude** [comment]
If it was the "Get all blooks" It just unlocks it in game. You must be in a game lobby to use it.

**Comment by manchilds** [comment]
game lobby?

**Comment by R3nH4s1ssu3s** [comment]
the game lobby is where you join in a game and you are waiting for other players.
with the character picker, yknow?

**Comment by manchilds** [comment]
so do we need to host the game or be in it?

**Comment by Hankypoo7** [comment]
be in it, like when your teacher hosts a game, you type in the game code, and on the waiting screen you do it then
