### ISSUE TITLE
issue tower defense hack

### ISSUE THREAD

**Issue by ryanrexhulk** [lol-jude/Blooket-Hacks#101]
when i say javascript and put the code in it just says to follow someones twitter and doesnt ask me how much coins i want

**Comment by lol-jude** [comment]
We are working on a fix for that.

**Comment by Sterngostling555** [comment]
you can also use inspect element with console commands

**Comment by ryanrexhulk** [comment]
i cant use inspect cuz its shaded in and i cant click it

**Comment by Sterngostling555** [comment]
It usually works for me

**Comment by Sterngostling555** [comment]
try to use ctrl+shift+i

**Comment by Sterngostling555** [comment]
works for me just I cant use the hack it's broken right now

**Comment by USSGreenhornet** [comment]
the coin hack works for TD but after i can't place any other towers

**Comment by Hankypoo7** [comment]
yeah
