### ISSUE TITLE
it kicks you if i use a certain code. anyone know how to fix?

### ISSUE THREAD

**Issue by someoneyoudontknow22** [lol-jude/Blooket-Hacks#109]

**Comment by possiblemonkeygamer** [comment]
you got banned

**Comment by someoneyoudontknow22** [comment]
i did? then how come i can still play blooket

**Comment by someoneyoudontknow22** [comment]
also use  this is pretty op  https://pxtrez.com/

**Comment by lol-jude** [comment]
Some hacks are really glitchy, make sure you don't just use a singe hack so much and you should be ok.

**Comment by godlygamer123** [comment]
great link
