### ISSUE TITLE
this is copyright of gliz work/stolen code

### ISSUE THREAD

**Issue by Belook12** [lol-jude/Blooket-Hacks#12]
This is a copyright of gliz work. If you do not take this down he can take legal actions to take this down. He'd like to talk to you

Join his discord server https://discord.gg/6VQawGjv lol-jude.

**Comment by Hack700** [comment]
yeah take it down

**Comment by pazza223** [comment]
@lol-jude you NEED to read this ishue. this is no joke, gliz wants to talk to you means you F'd up.

**Comment by Snowflake-Coder-H2o** [comment]
@pazza223 Shut up man you ctole my work too!

**Comment by kgsensei** [comment]
> This is a copyright of gliz work. If you do not take this down he can take legal actions to take this down. He'd like to talk to you
> 
> Join his discord server https://discord.gg/6VQawGjv lol-jude.

Just look at his account. He's just trying to be a hero and protect code that was taken down for violating community guidelines and also targeting repositories owned by individuals who have written their own code and have nothing to do with the person he's claiming. Oh yeah, and the somewhat false legal claims. Don't do anything, just ignore.

**Comment by aloevera1210** [comment]
> > This is a copyright of gliz work. If you do not take this down he can take legal actions to take this down. He'd like to talk to you
> > Join his discord server https://discord.gg/6VQawGjv lol-jude.
> 
> Just look at his account. He's just trying to be a hero and protect code that was taken down for violating community guidelines and also targeting repositories owned by individuals who have written their own code and have nothing to do with the person he's claiming. Oh yeah, and the somewhat false legal claims. Don't do anything, just ignore.

preach bro
