### ISSUE TITLE
Code doe not seem to work.

### ISSUE THREAD

**Issue by Eschatology3** [lol-jude/Blooket-Hacks#125]
I pasted the code in the URL, pressed enter as instructed, and nothing happened.
![Screenshot 2022-05-09 10 43 20 AM](https://user-images.githubusercontent.com/104865184/167446957-47ef4324-1590-4e56-8b3c-7837e6f19450.png)

**Comment by lol-jude** [comment]
Which one?

**Comment by ratlicker69420** [comment]
I have the same issue, and I was trying to use the chest esp... I'm sure that it's just a little extra thing I need to do

**Comment by Hankypoo7** [comment]
that hack is broken, we woll be working on a fix
