### ISSUE TITLE
Get all blooks in game is only temporary

### ISSUE THREAD

**Issue by CowCowCowCowCowCow** [lol-jude/Blooket-Hacks#131]
Can you pls fix that and provide instructions on how to make it permanent
Also you need to add dino box blooks, lovely frog, the spring frog thingy and the new blooks

**Comment by lol-jude** [comment]
It's impossible to be permanent, you also can't re add old updates.

**Comment by godlygamer123** [comment]
that is sad

**Comment by Hankypoo7** [comment]
yeah
