### ISSUE TITLE
This man is a skid

### ISSUE THREAD

**Issue by Apersonvr** [lol-jude/Blooket-Hacks#154]
Skid Skid Skid Skid Skid Skid Skid Skid Skid Skid Skid Skid Skid Skid Skid Skid Skid Skid Skid Skid Skid Skid Skid Skid

**Comment by lol-jude** [comment]
Nice issue

**Comment by ratlicker69420** [comment]
so true king

**Comment by Apersonvr** [comment]
imagen stealing from schoolcheats.net
