### ISSUE TITLE
Stop acting like you did everything

### ISSUE THREAD

**Issue by RattyBoi** [lol-jude/Blooket-Hacks#161]
Glixzzy was the original coder for the blooket hacks, he was here before you were, you made your account in Febuary, I have been using his hacks since December, although yes, his account has been deleted a few times, and posted the hacks to the school cheats website, the hacks are still owned by him. Maybe if you stopped being so immature and stealing all the credit for Glixzzy's hard work, maybe things will work out for you.

**Comment by VillainsRule4000** [comment]
@RattyBoi So true! There is PROOF #160.

**Comment by cursxdforlife** [comment]
@rattyboi my case lies here

**Comment by VillainsRule4000** [comment]
@cursxdforlife I am upvoting

**Comment by cursxdforlife** [comment]
ive giot more proof now 
<img width="899" alt="image" src="https://user-images.githubusercontent.com/98692335/168644183-a5b69428-7d53-4ae9-92e9-fe0804446cfe.png">

**Comment by RattyBoi** [comment]
@lol-jude What's wrong? You closed my issue because you are trying to hide the fact that you are a fraud claiming to have made all of the coding for the blooket hacks? It makes you all the more suspicious. Because you are trying to hide pure evidence, that you did none of the work, and are just taking credit for the blooket hacks.
