### ISSUE TITLE
EVERYONE LOOK HERE FOR THE TRUTH

### ISSUE THREAD

**Issue by cursxdforlife** [lol-jude/Blooket-Hacks#163]
<img width="948" alt="image" src="https://user-images.githubusercontent.com/98692335/168641709-18afa2eb-669f-4223-b3ea-ea4871ce9e58.png">

**Comment by cursxdforlife** [comment]
what a scam

**Comment by VillainsRule4000** [comment]
@cursxdforlife so true

**Comment by VillainsRule4000** [comment]
@lol-jude ANSWER TO THIS SCAM

**Comment by VillainsRule4000** [comment]
@cursxdforlife I was off for a bit, now I'm here.

**Comment by Plastiz** [comment]
@lol-jude  you shouldn't close this issue.  It really taints a bad image for u
