### ISSUE TITLE
bro you dumbass

### ISSUE THREAD

**Issue by Tech219** [lol-jude/Blooket-Hacks#168]
*"I am in the process of taking legal action against someone stealing my code and posting it as their own. They modified my code as well as deleted all credit towards me. Do not steal my work as I will take legal actions."* did you make this months ago? gliz Made it you dumbass he didn't do any of this shit dumbass .. also you aren't in trouble with anybody with legal claims goofy ass ☠️

**Comment by USSGreenhornet** [comment]
gilx got banned he might have given lol-jude the code
