### ISSUE TITLE
screen gets messed up after usage 

### ISSUE THREAD

**Issue by Sumrandomkid** [lol-jude/Blooket-Hacks#25]
when you use ANY hack it puts a box on the screen can you remove of fix it somehow?
![Screenshot 2022-03-29 12 05 35 PM](https://user-images.githubusercontent.com/102557964/160666994-9c41df7c-d3c8-4993-91fe-7004f1d8a74b.png)

**Comment by lol-jude** [comment]
go into inspect and click backspace after selecting the element, or reload your page

**Comment by Sumrandomkid** [comment]
And restarting the page won't work
