### ISSUE TITLE
Getcash.js from factory isnt working

### ISSUE THREAD

**Issue by Hankypoo7** [lol-jude/Blooket-Hacks#26]
when I do it it removes cash numbe
![Screenshot 2022-03-30 10 04 54 PM](https://user-images.githubusercontent.com/100436822/160968114-275dd209-c92a-4053-a128-8a75cd34cf52.png)
Look in the top right

**Comment by lkeld** [comment]
try again, a dialogue should open asking how much cash you want to add.

**Comment by Hankypoo7** [comment]
ok

**Comment by lol-jude** [comment]
If this has not worked I can push an update. Let me know.

**Comment by Hankypoo7** [comment]
ok

**Comment by eddieitis** [comment]
> If this has not worked I can push an update. Let me know.

hasnt woked for me in a long time and the cypto one for cash just straight up kicks me out the game fyi

**Comment by Hankypoo7** [comment]
yeha

**Comment by Hankypoo7** [comment]
*yeah

**Comment by lol-jude** [comment]
pushing update.
