### ISSUE TITLE
Spam open boxes is down

### ISSUE THREAD

**Issue by Lukatron300** [lol-jude/Blooket-Hacks#28]

**Comment by lol-jude** [comment]
I was using it earlier when asked for a box name did you use a capital like "Safari"

**Comment by Hankypoo7** [comment]
for me (i did javascript: ) i did the "Bot Box" and it said, 'could not find that box'

**Comment by lol-jude** [comment]
Don't type box afterward only type "Bot"

**Comment by Hankypoo7** [comment]
ok

**Comment by Lukatron300** [comment]
Thanks a ton, it worked! :)
