### ISSUE TITLE
Can I use one of your hacks If i credit you?

### ISSUE THREAD

**Issue by Hankypoo7** [lol-jude/Blooket-Hacks#29]
on my respository I would use the 'spam open boxes' hack if I credit you in the read.me?
btw thanks for showing me how to use the box spam open hack :)

**Comment by theBlaize** [comment]
just fork it and then it is yours

**Comment by lol-jude** [comment]
as long as you dont steal my work you are ok

**Comment by lol-jude** [comment]
aka saying its yours

**Comment by Hankypoo7** [comment]
ok
