### ISSUE TITLE
is it not just from when Glizzy had it

### ISSUE THREAD

**Issue by theBlaize** [lol-jude/Blooket-Hacks#30]
is it not just from when Glizzy had it?

**Comment by Hankypoo7** [comment]
no, @lol-jude coded most of them.

**Comment by lol-jude** [comment]
Exactly, I used bits from giz but coded the rest.

**Comment by RattyBoi** [comment]
> Exactly, I used bits from giz but coded the rest.
If this is true, then how come every single time we use the hacks it says, "Made by Gliz?"
