### ISSUE TITLE
THIS IS NEEEDED

### ISSUE THREAD

**Issue by willutgilugpiulg** [lol-jude/Blooket-Hacks#36]
PLEASE GET A HACK WHERE IT UPS THE PERCENTS TO GET GOOD BLOOKS IN THE STORE PLEASE LITERALLY IT WILL MAKE YOU FAMOUS BECAUSE NOBODY HAS DONE It, SOO BE THE FIRST TO.

**Comment by yapgamer** [comment]
that is already built into blooket

**Comment by lol-jude** [comment]
It's impossible to modify the chances of the Blooket API giving you blooks. Sorry!

**Comment by willutgilugpiulg** [comment]
ive opened the safari box 1,269 times and still has not gotten the rainbow panda

**Comment by yapgamer** [comment]
> ive opened the safari box 1,269 times and still has not gotten the rainbow panda

youll get it soon enough
