### ISSUE TITLE
A Little Bug?

### ISSUE THREAD

**Issue by Beep404-Boop404** [lol-jude/Blooket-Hacks#39]
When I play the games live, I used the hack and it looks like I've added the crypto, or cash, or weight. But in reality, it doesn't add the stuff(crypto, cash, or weight). Can you fix it? If it is fixed, I would be very pleased!

**Comment by lol-jude** [comment]
Yes, it may take a bit but I will push an update.

**Comment by Beep404-Boop404** [comment]
Thanks! :)
