### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by candace2009** [lol-jude/Blooket-Hacks#42]
how do you get the code or the bookmark

**Comment by yapgamer** [comment]
so click on gamemode then click the hack you want to use, click the little button next to code that 2 sqaures overlapping eachother

**Comment by teodaboi** [comment]
noice

**Comment by teodaboi** [comment]
how do you open it after that

**Comment by teodaboi** [comment]
thanks

**Comment by yapgamer** [comment]
> go to the blooket gamemode that you want to hack in, type this,"Javascript:(pasted code)" It should look like this ![Screenshot 2022-04-11 8 26 44 PM](https://user-images.githubusercontent.com/100436822/162860188-96398105-f065-4b10-a4db-d7b545e2f56f.png) then just click enter hope this helped :)

I didnt know you could use it in the url

**Comment by underzellis** [comment]
so i tried to copy the raw but it says somthing went wrong, any help?

**Comment by yapgamer** [comment]
> so i tried to copy the raw but it says somthing went wrong, any help?

did you click the button that said raw or the 2 overlapping squares to the right of it?

**Comment by Hankypoo7** [comment]
highlight all the text

**Comment by godlygamer123** [comment]
sometimes it works and some times it doesn't
