### ISSUE TITLE
This your work?

### ISSUE THREAD

**Issue by GlixzzyBlooketHacks** [lol-jude/Blooket-Hacks#50]
These was made from glixzzy lol all credit go to glixzzy

**Comment by GlixzzyBlooketHacks** [comment]
I know that because all the hacks when u use them it says Made By Gliz my twitter lol

**Comment by Hankypoo7** [comment]
he got the hacks from schoolcheats.net so go annoy schoolcheats.net not this repo

**Comment by lol-jude** [comment]
Bro can you stfu. Gliz is IP banned on GitHub and said his appeal was denied. IE: You are fake so please stfu.
