### ISSUE TITLE
How

### ISSUE THREAD

**Issue by ClashProof** [lol-jude/Blooket-Hacks#54]
How to use the Global Add Tokens

**Comment by Hankypoo7** [comment]
go to the url bar when you are in blooket
![Screenshot 2022-04-18 9 42 25 AM](https://user-images.githubusercontent.com/100436822/163824930-26969fa2-b8dd-4e09-bc0a-16a815298f30.png)
type   "  javascript:  "
then paste your code in
it should look like this
![Screenshot 2022-04-18 9 45 50 AM](https://user-images.githubusercontent.com/100436822/163825308-ed7728b2-e31f-4f0a-826a-5f43e30cbc72.png)
then, refresh your page and you should be good to go

**Comment by KimaKween** [comment]
or, if u are on windows, click inspect (Ctrl-Shift-C), and paste it into console

**Comment by KimaKween** [comment]
then refresh the page

**Comment by Hankypoo7** [comment]
@KimaKween  its easier this way, its faster.
