### ISSUE TITLE
not working scripts

### ISSUE THREAD

**Issue by Sterngostling555** [lol-jude/Blooket-Hacks#58]
Most of these scripts for the games don't work like the crypto hack and gold quest hacks, please update them as they don't work right now.

**Comment by Hankypoo7** [comment]
we can try to fix them, but as far as I know, they all work except for crypto and gold quest

**Comment by Sterngostling555** [comment]
ok thanks.

**Comment by Sterngostling555** [comment]
Also, the sell dupe blooks wasn't working for me. And the Cafe max out food only made the food trays change color, but nothing happened.

**Comment by Sterngostling555** [comment]
wait the sell dupe blooks works now

**Comment by lol-jude** [comment]
Sometimes the scripts are glitchy due to Blooket trying to prevent all of this.
