### ISSUE TITLE
LICENSE: Warning

### ISSUE THREAD

**Issue by Colack** [lol-jude/Blooket-Hacks#64]
Just a warning here, 

As you said in your README.md file, you are going to be taking legal action against these people. However, you have a MIT License, meaning people can edit and re-distribute your code for free.

I recommend changing your license.

**Comment by Hankypoo7** [comment]
thanks for the warning, we will fix

**Comment by lol-jude** [comment]
The person was uploading it as theirs, removing my credit, and modified it which is against the license but I can look into others.

**Comment by lol-jude** [comment]
Thank you alot I have changed my license.

**Comment by Colack** [comment]
Well, you were using the MIT license, which allows for redistribution, modification, and merging of the software.\
If you were still using the MIT license, I could take your code right now, and sell it.
But, good thing your not haha
