### ISSUE TITLE
School Chromebook?

### ISSUE THREAD

**Issue by GameGuyLol** [lol-jude/Blooket-Hacks#80]
You said that they were all still working but they don't work on a school chromebook.
I don't know if this is because of the device or because of the admin.

Please respond or fix if you can,
thanks.

**Comment by Hankypoo7** [comment]
I use a school computer, and it works

**Comment by Hankypoo7** [comment]
if you are confused how i can show you how to do the hacks

**Comment by lol-jude** [comment]
As long as you can use console it should work. Some hacks may be down but without console there are other ways Hanky knows of.

**Comment by Hankypoo7** [comment]
Here's how:
go to the url bar when you are in blooket
![Screenshot 2022-04-18 9 42 25 AM](https://user-images.githubusercontent.com/100436822/163824930-26969fa2-b8dd-4e09-bc0a-16a815298f30.png)
type   "  **javascript:**  "
then paste your code in
it should look like this
![Screenshot 2022-04-18 9 45 50 AM](https://user-images.githubusercontent.com/100436822/163825308-ed7728b2-e31f-4f0a-826a-5f43e30cbc72.png)
(the text in the middle)
then, refresh your page and you should be good to go

**Comment by godlygamer123** [comment]
lol

**Comment by godlygamer123** [comment]
type the colon

**Comment by danielolol932** [comment]
es que pones pega el codigo pero yo no tengo ningun codigo me lo puede pasar alguien porfavor
