### ISSUE TITLE
How do i use the hacks

### ISSUE THREAD

**Issue by KrisHacked** [lol-jude/Blooket-Hacks#83]
how do i use the hacks i copied the code into the console and nothing happened

**Comment by Hankypoo7** [comment]
go to the url bar when you are in blooket
![Screenshot 2022-04-18 9 42 25 AM](https://user-images.githubusercontent.com/100436822/163824930-26969fa2-b8dd-4e09-bc0a-16a815298f30.png)
type   "  **javascript:**  "
then paste your code in
it should look like this
![Screenshot 2022-04-18 9 45 50 AM](https://user-images.githubusercontent.com/100436822/163825308-ed7728b2-e31f-4f0a-826a-5f43e30cbc72.png)
(the text in the middle)
then, refresh your page and you should be good to go

**Comment by unweal** [comment]
what? i don not get this
