### ISSUE TITLE
Square Pops Up and One Time Use

### ISSUE THREAD

**Issue by QuantumQ000** [lol-jude/Blooket-Hacks#91]
![Screenshot 2022-04-29 11 42 11 AM](https://user-images.githubusercontent.com/104102780/166006855-d1a2bc5d-fc64-4c26-b34c-2db8014c54bd.png)
Square Pops Up:
A hollow square pops up in the corner when I use one of the hacks.

One Time Use:
I can only use one hack each time I open bloolet because of the twitter box and the random square.

**Comment by Hankypoo7** [comment]
the one time use is because it isnt actually encryping code in the blooket database, so it is impossible to legaly fix, as for the twitter we can fix, and we will work on it. The box however, cant have anything done to romove it
