### ISSUE TITLE
not an issue but a question

### ISSUE THREAD

**Issue by pixthehe** [lol-jude/Blooket-Hacks#97]
hi okay I know javascript a bit and I was just wondering how you make this stuff. Is their a library i should know of on npm? Is it just messing with some objects? You dont need to tell me the code is obfuscated as I can see but I would love to contribute and know how to do this

**Comment by FiReLScar** [comment]
I just want to get rid of the stupid message so my teacher doesn't say shit. But yeah it's obfuscated to hell so big oof.
